// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WAMsSfsp_-K343N5ObKgNumd7SvdYyc',
    appId: '1:322336638669:web:6208d2a5801ef5cf0a0b84',
    messagingSenderId: '322336638669',
    projectId: 'scrapify-9bcaa',
    authDomain: 'scrapify-9bcaa.firebaseapp.com',
    storageBucket: 'scrapify-9bcaa.appspot.com',
    measurementId: 'G-N9X8LEEJ47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-q-_hlA_oJoR7l0V6hutMH3v2Tvp7gp4',
    appId: '1:322336638669:android:15ccdc4df6d12ab50a0b84',
    messagingSenderId: '322336638669',
    projectId: 'scrapify-9bcaa',
    storageBucket: 'scrapify-9bcaa.appspot.com',
  );
}
